name: Build and Publish Odoo Fresh DB
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build_publish_odoo_freshDB.yml"
      - "package/docker/resources/database/**"
      - "package/docker/freshDB/**"

env:
  BAHMNI_VERSION: 0.94

jobs:
  docker-build-publish:
    name: Docker Build & Publish Odoo Fresh DB
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          file: package/docker/freshDB/Dockerfile
          push: true
          tags: bahmni/odoo-10-db:fresh-${{env.BAHMNI_VERSION}}-${{github.run_number}},bahmni/odoo-10-db:fresh-latest

